### ISSUE TITLE
Protect the master branch

### ISSUE THREAD

**Issue by dkess** [ocf/etc#15]
GitHub supports "protecting" branches, only allowing PRs to be merged if they pass certain checks.

This requires using the ["status check"](https://developer.github.com/v3/repos/statuses/) feature of GitHub. Basically, we need Jenkins to tell GitHub that a commit hash is OK to be merged. While we have automatic Jenkins builds, none of our repos use the status check feature.

It looks like the GitHub Jenkins plugin supports this (see https://wiki.jenkins.io/display/JENKINS/GitHub+Plugin#GitHubPlugin-Pipelineexamples), so it's just a matter of adding this to the Jenkinsfile. We might also want to put this functionality in the [shared pipeline repository](https://github.com/ocf/shared-pipeline) if we expect it to be used in other repos.

**Comment by cg505** [comment]
This is already in the shared pipeline/repo config. We just had to give the "Bots" team under the ocf org Write access to this repo. This is done.

I started drafting some information at https://docs.google.com/document/d/1Y86JAEh8iiEOMFAMM0xx3L62rueSr-HUe3Ugh-ufYeU/edit. We also may need to update https://www.ocf.berkeley.edu/docs/staff/backend/jenkins/#h2_jenkins-for-github-projects.
